$env:SIMULATOR_PORT="9087"
$env:NODE_ORACLEDB_USER="INTE_NODO_ONLINE_2"
$env:NODE_ORACLEDB_PASSWORD="INTE_NODO_ONLINE_2"
$env:NODE_ORACLEDB_CONNECTIONSTRING="10.8.3.222:1523/NDPSPCS"
node simulator.js
